name: flutter_clean_architecture_template
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  # Image
  cached_network_image: ^3.3.1

  # Handle State
  dartz: ^0.10.1

  # Device preview to test app in all devices
  device_preview: ^1.1.0

  # Fetch Data From Api
  dio: ^5.4.0

  # Translation
  easy_localization: ^3.0.3
  
  # Compare objects
  equatable: ^2.0.5

  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3

  # Code generation for data classes
  freezed: ^2.4.6


  # Dependency Injection
  get_it: ^7.6.7
  json_annotation: ^4.8.1

  # Logging Interceptor
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  # fonts:
  # - family: Georgia
  #   fonts:
  #     - asset: assets/fonts/Georgia/Georgia.ttf